// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9rP9c-bSMNvPlYnY1bwOYd-MSRRfzk1Q',
    appId: '1:416845303939:web:0c6b481b9d4c24a83a0bb6',
    messagingSenderId: '416845303939',
    projectId: 'iamm-b226f',
    authDomain: 'iamm-b226f.firebaseapp.com',
    storageBucket: 'iamm-b226f.appspot.com',
    measurementId: 'G-56GZGJH215',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIu4zkBsbinCRFwmNBirMEEp49vLbam9g',
    appId: '1:416845303939:android:329a3bc95b30fcc53a0bb6',
    messagingSenderId: '416845303939',
    projectId: 'iamm-b226f',
    storageBucket: 'iamm-b226f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBp5uHzTAXBw2YUi0P52cEsDQQ0y7Q3n8',
    appId: '1:416845303939:ios:435480f576a367b53a0bb6',
    messagingSenderId: '416845303939',
    projectId: 'iamm-b226f',
    storageBucket: 'iamm-b226f.appspot.com',
    iosBundleId: 'com.example.iamDouaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBp5uHzTAXBw2YUi0P52cEsDQQ0y7Q3n8',
    appId: '1:416845303939:ios:1665dc90d3e98e303a0bb6',
    messagingSenderId: '416845303939',
    projectId: 'iamm-b226f',
    storageBucket: 'iamm-b226f.appspot.com',
    iosBundleId: 'com.example.iamDouaa.RunnerTests',
  );
}
